apiVersion: apps/v1
kind: Deployment
metadata:
  name: dinner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dinner
  template:
    metadata:
      labels:
        app: dinner
    spec:
      containers:
      - image: okteto.dev/dinner:latest
        name: dinner
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "2867bf90-9328-4bdb-8f4e-286b305ae8ef"
        - name: Vless_Path
          value: "/vldd"
        - name: Vmess_UUID
          value: "2867bf90-9328-4bdb-8f4e-286b305ae8ef"
        - name: Vmess_Path
          value: "/vm666"
        - name: Share_Path
          value: "/v2link"
